name 'thbe-ssh'
version '0.2.0'

author 'Thomas Bendler <project@bendler-net.de>'
license 'GPLv3'
project_page 'https://github.com/thbe/puppet-ssh.git'
source 'https://github.com/thbe/puppet-ssh.git'
summary 'SSH management module'
description 'SSH management module'
dependency 'puppetlabs/stdlib', '>=2.2.0'
